--1
-- PAQUETE ARITMETICA – Especificacion
-- PACKAGE_ARITMETICA.SQL 
CREATE OR REPLACE
PACKAGE ARITMETICA IS
VERSION NUMBER:=1.0;
PROCEDURE MOSTRARINFO;
FUNCTION SUMA (A NUMBER, B NUMBER)
RETURN NUMBER;
FUNCTION RESTA(A NUMBER, B NUMBER)
RETURN NUMBER;
FUNCTION MULTIPLICACION(A NUMBER, B NUMBER)
RETURN NUMBER;
FUNCTION DIVISION(A NUMBER, B NUMBER)
RETURN NUMBER;
END ARITMETICA;
-- PAQUETE ARITMETICA – Cuerpo
-- PACKAGE_BODY_ARITMETICA.SQL 
CREATE OR REPLACE
PACKAGE BODY ARITMETICA IS
    PROCEDURE MOSTRARINFO IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('VERSION DEL PAQUETE ' || VERSION);
    END MOSTRARINFO;
    FUNCTION SUMA (A NUMBER, B NUMBER)
    RETURN NUMBER;
    BEGIN
        RETURN A+B;
    END SUMA;
    FUNCTION RESTA (A NUMBER, B NUMBER)
    RETURN NUMBER;
    BEGIN
        RETURN A-B;
    END RESTA;
    FUNCTION MULTIPLICACION (A NUMBER, B NUMBER)
    RETURN NUMBER;
    BEGIN
        RETURN A*B;
    END MULTIPLICACION;
    FUNCTION DIVISION (A NUMBER, B NUMBER)
    RETURN NUMBER;
    BEGIN
        RETURN A/B;
    END DIVISION;
END ARITMETICA;
BEGIN
  ARITMETICA.MOSTRAR_INFO;
END;
/

SELECT ARITMETICA.SUMA(4,3) FROM DUAL;
SELECT ARITMETICA.RESTA(4,3) FROM DUAL;
SELECT ARITMETICA.MULTIPLICA(4,3) FROM DUAL;
SELECT ARITMETICA.DIVIDE(4,3) FROM DUAL;
--2 2. Al paquete anterior añade una función llamada RESTO que reciba dos parámetros, el dividendo y el divisor, y devuelva el resto de la división
-- PAQUETE ARITMETICA – Especificacion
-- PACKAGE_ARITMETICA.SQL 
CREATE OR REPLACE
PACKAGE ARITMETICA IS
VERSION NUMBER:=1.0;
PROCEDURE MOSTRARINFO;
FUNCTION SUMA (A NUMBER, B NUMBER)
RETURN NUMBER;
FUNCTION RESTA(A NUMBER, B NUMBER)
RETURN NUMBER;
FUNCTION MULTIPLICACION(A NUMBER, B NUMBER)
RETURN NUMBER;
FUNCTION DIVISION(A NUMBER, B NUMBER)
RETURN NUMBER;
FUNCTION RESTO(DIVIDENDO NUMBER, DIVISOR NUMBER)
RETURN NUMBER;
END ARITMETICA;
-- PAQUETE ARITMETICA – Cuerpo
-- PACKAGE_BODY_ARITMETICA.SQL 
CREATE OR REPLACE
PACKAGE BODY ARITMETICA IS
    PROCEDURE MOSTRARINFO IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('VERSION DEL PAQUETE ' || VERSION);
    END MOSTRARINFO;
    FUNCTION SUMA (A NUMBER, B NUMBER)
    RETURN NUMBER;
    BEGIN
        RETURN A+B;
    END SUMA;
    FUNCTION RESTA (A NUMBER, B NUMBER)
    RETURN NUMBER;
    BEGIN
        RETURN A-B;
    END RESTA;
    FUNCTION MULTIPLICACION (A NUMBER, B NUMBER)
    RETURN NUMBER;
    BEGIN
        RETURN A*B;
    END MULTIPLICACION;
    FUNCTION DIVISION (A NUMBER, B NUMBER)
    RETURN NUMBER;
    BEGIN
        RETURN A/B;
    END DIVISION;
    FUNCTION RESTO (DIVIDENDO NUMBER, DIVISOR NUMBER)
    RETURN NUMBER;
    BEGIN
        RETURN DIVIDENDO%DIVISOR;
END ARITMETICA;
BEGIN
  ARITMETICA.MOSTRAR_INFO;
END;
/
SELECT ARITMETICA.SUMA(4,3) FROM DUAL;
SELECT ARITMETICA.RESTA(4,3) FROM DUAL;
SELECT ARITMETICA.MULTIPLICA(4,3) FROM DUAL;
SELECT ARITMETICA.DIVIDE(4,3) FROM DUAL;
SELECT ARITMETICA.RESTO(6,2) FROM DUAL;
--3 Al paquete anterior añade un procedimiento sin parámetros llamado AYUDA que muestre un mensaje por pantalla de los procedimientos y funciones disponibles en el paquete, su utilidad y forma de uso.
-- PAQUETE ARITMETICA – Especificacion
-- PACKAGE_ARITMETICA.SQL 
--PROCEDIMIENTOS Y FUNCIONES DISPONIBLES EN EL PAQUETE
CREATE OR REPLACE
PACKAGE ARITMETICA IS
VERSION NUMBER:=1.0;
PROCEDURE MOSTRARINFO;
PROCEDURE AYUDA;
FUNCTION SUMA (A NUMBER, B NUMBER)
RETURN NUMBER;
FUNCTION RESTA(A NUMBER, B NUMBER)
RETURN NUMBER;
FUNCTION MULTIPLICACION(A NUMBER, B NUMBER)
RETURN NUMBER;
FUNCTION DIVISION(A NUMBER, B NUMBER)
RETURN NUMBER;
FUNCTION RESTO(DIVIDENDO NUMBER, DIVISOR NUMBER)
RETURN NUMBER;
END ARITMETICA;
-- PAQUETE ARITMETICA – Cuerpo
-- PACKAGE_BODY_ARITMETICA.SQL 
--UTILIDAD
CREATE OR REPLACE
PACKAGE BODY ARITMETICA IS
    PROCEDURE MOSTRARINFO IS
    A NUMBER:=4;
    B NUMBER:=3;
    SUMAR NUMBER;
    RESTAR NUMBER;
    DIVIDENDO NUMBER:=5
    DIVISOR NUMBER:=2;
    RESTOO NUMBER;
    BEGIN
        DBMS_OUTPUT.PUT_LINE('VERSION DEL PAQUETE ' || VERSION);
    END MOSTRARINFO;
    FUNCTION SUMA (A NUMBER, B NUMBER)
    RETURN NUMBER;
    BEGIN
        RETURN A+B;
    END SUMA;
    FUNCTION RESTA (A NUMBER, B NUMBER)
    RETURN NUMBER;
    BEGIN
        RETURN A-B;
    END RESTA;
    FUNCTION MULTIPLICACION (A NUMBER, B NUMBER)
    RETURN NUMBER;
    BEGIN
        RETURN A*B;
    END MULTIPLICACION;
    FUNCTION DIVISION (A NUMBER, B NUMBER)
    RETURN NUMBER;
    BEGIN
        RETURN A/B;
    END DIVISION;
    FUNCTION RESTO (DIVIDENDO NUMBER, DIVISOR NUMBER)
    RETURN NUMBER;
    BEGIN
        RETURN DIVIDENDO%DIVISOR;
    END RESTO;
    PROCEDURE AYUDA IS
    BEGIN 
        SELECT ARITMETICA.SUMA(A,B) INTO SUMAR FROM DUAL;
        SELECT ARITMETICA.RESTAR(A,B) INTO RESTAR FROM DUAL;
        DBMS_OUTPUT.PUT_LINE('LA SUMA DEL VALOR ' || A || ' Y ' || B || ' DA ' || SUMAR || 'Y LA RESTA ' || RESTAR );
    END AYUDA;
END ARITMETICA;
--FORMA DE USO
BEGIN
  ARITMETICA.MOSTRAR_INFO;
END;
BEGIN
    ARITMETICA.AYUDA;
END;
/
SELECT ARITMETICA.SUMA(4,3) FROM DUAL;
SELECT ARITMETICA.RESTA(4,3) FROM DUAL;
SELECT ARITMETICA.MULTIPLICA(4,3) FROM DUAL;
SELECT ARITMETICA.DIVIDE(4,3) FROM DUAL;
SELECT ARITMETICA.RESTO(6,2) FROM DUAL;
--4 
-- PAQUETE GESTION – Especificación
-- PACKAGE_GESTION.SQL
--PROCEDIMIENTOS Y FUNCIONES DISPONIBLES EN EL PAQUETE
CREATE OR REPLACE
PACKAGE GESTION 
IS
    PROCEDURE CREAR_DEP (nombre VARCHAR2, presupuesto NUMBER);
    FUNCTION NUM_DEP (nombre VARCHAR2) 
    RETURN NUMBER;
    PROCEDURE MOSTRAR_DEP (numero NUMBER);
    PROCEDURE BORRAR_DEP (numero NUMBER);
    PROCEDURE MODIFICAR_DEP (numero NUMBER, presupuesto NUMBER);
END GESTION;
-- PAQUETE GESTION – Cuerpo
-- PACKAGE_body_GESTION.SQL
--UTILIDAD
CREATE OR REPLACE
PACKAGE BODY GESTION IS
    PROCEDURE CREAR_DEP(nombre,presupuesto)
    IS
    BEGIN
        CREATE TABLE DEPARTAMENTO
        (
            nombre VARCHAR2,
            presupuesto NUMBER
        );
    END CREAR_DEP;
    FUNCTION NUM_DEP(nombre VARCHAR2)
    RETURN NUMBER;
    RESULTADO NUMBER;
    BEGIN
        ALTER TABLE DEPARTAMENTO ADD CONSTRAINT NUM_DEP NUMBER;
        SELECT NUM_DEP INTO RESULTADO FROM DEPARTAMENTO D WHERE D.NOMBRE LIKE nombre;
        RETURN RESULTADO;
    END NUM_DEP;
    PROCEDURE MOSTRAR_DEP(numero NUMBER)
    IS
    NOMDEPAR VARCHAR2 ;
    BEGIN 
        SELECT NOMBRE INTO NOMDEPAR FROM DEPARTAMENTO D WHERE D.NUMDEP=numero;
        DBMS_OUTPUT.PUT_LINE('EL DEPARTAMENTO NUMERO ' || numero || ' SE LLAMA ' ||NOMDEPAR);
    END MOSTRAR_DEP;
    PROCEDURE BORRAR_DEP(numero NUMBER)
    IS
    BEGIN
        DELETE FROM DEPARTAMENTO D WHERE D.NUMDEP=numero;
    END BORRAR_DEP;
    PROCEDURE MODIFICAR_DEP(numero NUMBER, presupuestonuevo NUMBER)
    IS
    BEGIN
        UPDATE DEPARTAMENTO SET presupuesto=presupuestonuevo WHERE NUMDEP=numero;
    END MODIFICAR_DEP;
END GESTION;
--FORMA DE USO
BEGIN 
    GESTION.CREAR_DEP('VENTAS', 20000);
END;
SELECT FUNCTION GESTION.NUM_DEP(4) FROM DUAL;
BEGIN 
    GESTION.MOSTRAR_DEP(4);
END;
BEGIN 
    GESTION.BORRAR_DEP(5);
END;
BEGIN 
    GESTION.MODIFICAR_DEP(4, 40000);
END;