--DROP TABLE PROFESORES
--DROP TABLE CURSOS
--DROP TABLE ALUMNOS

CREATE TABLE PROFESORES
(
    NOMBRE VARCHAR2(10),
    APELLIDO1 VARCHAR2(10),
    APELLIDO2 VARCHAR2(10),
    DNI_PROFESORES VARCHAR2(9),
    DIRECCION VARCHAR2(10),
    TITULO VARCHAR2(10),
    GANA NUMBER(5),
    CONSTRAINT PK_PROFESORES PRIMARY KEY (DNI_PROFESORES)
)

CREATE TABLE CURSOS
(
    NOMBRE_CURSO VARCHAR2(10),
    CODIGO_CURSO VARCHAR2(10),
    DNI_PROFESOR VARCHAR2(10),
    MAXIMO_ALUMNOS NUMBER(3),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    NUM_HORAS NUMBER(4)
    CONSTRAINT PK_CURSOS PRIMARY KEY (CODIGO_CURSO),
    CONSTRAINT FK_CURSOS FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESORES (DNI_PROFESORES)
)

CREATE TABLE ALUMNOS
(
    NOMBRE VARCHAR2(10),
    APELLIDO1 VARCHAR2(10),
    APELLIDO2 VARCHAR2(10),
    DNI_ALUMNOS VARCHAR2(9),
    DIRECCION VARCHAR2(10),
    FECHA_NACIMIENTO DATE,
    SEXO VARCHAR2(1),
    CURSO NUMBER(1),
    CONSTRAINT PK_ALUMNOS PRIMARY KEY (DNI_ALUMNOS),
    CONSTRAINT FK_ALUMNOS FOREIGN KEY (CURSO) REFERENCES CURSOS (CODIGO_CURSO)
)

INSERT INTO PROFESORES
(NOMBRE,APELLIDO1,APELLIDO2,DNI_PROFESORES,DIRECCION,TITULO,GANA)
VALUES ('JUAN','ARCH','LOPEZ','32432455','PUERTO NEGRO, 4','ING. INFORMATICA',7500);

INSERT INTO PROFESORES
(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,TITULO,GANA)
VALUES ('MARIA','OLIVIA','RUBIO','43215643','JUAN ALFONSO 32','LDO.FIL.INGLESA',5400);

INSERT INTO CURSOS
(NOMBRE_CURSO,CODIGO_CURSO,DNI_PROFESOR,MAXIMO_ALUMNOS,FECHA_INICIO,FECHA_FIN,NUM_HORAS)
VALUES ('INGLES BASICO',1,'43215643',15,TO_DATE('01/11/00'),TO_DATE('22-DIC-00'),120);

INSERT INTO CURSOS
(NOMBRE_CURSO,CODIGO_CURSO,DNI_PROFESOR,MAXIMO_ALUMNOS,FECHA_INICIO,FECHA_FIN,NUM_HORAS)
VALUES ('ADMINISTRACION LINUX',2,'32432455',NULL,TO_DATE('01-SEPT-00'),NULL,80);

INSERT INTO ALUMNOS
(NOMBRE,APELLIDO1,APELLIDO2,DNI_ALUMNOS,DIRECCION,SEXO,FECHA_NACIMIENTO,CURSO)
VALUES ('LUCAS','MANILVA','LOPEZ','123523','ALHAMAR, 3','V',TO_DATE('01/11/79'),1);

INSERT INTO ALUMNOS
(NOMBRE,APELLIDO1,APELLIDO2,DNI_ALUMNOS,DIRECCION,SEXO,FECHA_NACIMIENTO,CURSO)
VALUES ('ANTONIA','LOPEZ','ALCANTARA','2567567','MANIQUI, 21','M',NULL,2);

INSERT INTO ALUMNOS
(NOMBRE,APELLIDO1,APELLIDO2,DNI_ALUMNOS,DIRECCION,SEXO,FECHA_NACIMIENTO,CURSO)
VALUES ('MANUEL','ALCANTARA','PEDROS','3123689','JULIAN, 2','V',NULL,1);

INSERT INTO ALUMNOS
(NOMBRE,APELLIDO1,APELLIDO2,DNI_ALUMNOS,DIRECCION,SEXO,FECHA_NACIMIENTO,CURSO)
VALUES ('JOSE','PEREZ','CABALLAR','4896765','JARCHA, 5','V',TO_DATE('03/02/77'),3);

INSERT INTO ALUMNOS
(NOMBRE,APELLIDO1,APELLIDO2,DNI_ALUMNOS,DIRECCION,SEXO,FECHA_NACIMIENTO,CURSO)
VALUES ('SERGIO','NAVAS','RETAL','123523',NULL,'P',NULL,1);
--VALOR DNI_ALUMNOS REPETIDO

INSERT INTO PROFESORES
(NOMBRE,APELLIDO1,APELLIDO2,DNI_PROFESORES,DIRECCION,TITULO,GANA)
VALUES ('JUAN','ARCH','LOPEZ','32432455','PUERTO NEGRO, 4','ING.INFORMATICA',NULL);
--SOLO MODIFICA EL VALOR GANA

INSERT INTO ESTUDIANTE
(NOMBRE,APELLIDO1,APELLIDO2,DNI_ALUMNOS,DIRECCION,SEXO,FECHA_NACIMIENTO)
VALUES ('MARIA','JAEN','SEVILLA','789678','MARTOS, 5','M',NULL)
--MENCIONA UNA TABLA ESTUDIANTE QUE NO EXISTE

UPDATE ALUMNOS SET FECHA_NACIMIENTO='23-DIC-1976' WHERE DNI_ALUMNOS LIKE '2567567';
UPDATE ALUMNOS SET CURSO=5 WHERE DNI_ALUMNOS LIKE '2567567';
DELETE FROM PROFESORES WHERE NOMBRE LIKE'LAURA' AND APELLIDO1 LIKE 'JIMENEZ';
ALTER TABLE CURSOS ADD NUMERO_ALUMNOS;
UPDATE ALUMNOS FECHA_NACIMIENTO='01/01/2012' WHERE FECHA_NACIMIENTO= NULL;
ALTER TABLE ALUMNOS DROP SEXO;
UPDATE PROFESORES SET GANA=GANA*1,2 WHERE TITULO LIKE ING. INFORMATICA;
UPDATE PROFESORES SET DNI_PROFESORES='1234567' WHERE NOMBRE LIKE JUAN AND APELLIDOS LIKE ARCH;
UPDATE PROFESORES SET DNI='7654321' WHERE TITULO LIKE 'ING. INFORMATICA';
UPDATE ALUMNOS SET SEXO='F' WHERE NOMBRE LIKE 'MARIA' AND APELLIDO1 LIKE 'JAEN';