--DROP CURSO
--DROP ALUMNO
--DROP MATRICULA
--DROP PROFESOR

CREATE TABLE CURSO
(
    CODIGO_CURSO VARCHAR2(10),
    NOMBRE VARCHAR2(10) UNIQUE,
    ALUMNOS_MAXIMO NUMBER(2),
    PROFESOR_ASIGNADO VARCHAR2(10),
    FECHA_INICIO DATE,
    FECHA_FINALIZACION DATE,
    HORAS_TOTALES NUMBER(3) NOT NULL,
    CONSTRAINT PK_CURSO PRIMARY KEY (CODIGO_CURSO)
)

CREATE TABLE ALUMNO
(
    DNI_ALUMNO VARCHAR2(10),
    NOMBRE VARCHAR2(10),
    APELLIDOS VARCHAR2(10),
    DIRECCION VARCHAR2(10),
    FECHA_NACIMIENTO DATE,
    SEXO VARCHAR2(1),
    CODIGO_CURSO VARCHAR2(10),
    ALUMNO_MATRICULADO VARCHAR2(10),
    CONSTRAINT PK_ALUMNO PRIMARY KEY (DNI_ALUMNO),
    CONSTRAINT FK2_MATRICULA FOREIGN KEY (DNI_ALUMNO) REFERENCES ALUMNO (DNI_ALUMNO)
)

CREATE TABLE PROFESOR 
(
    DNI_PROFESOR VARCHAR2(10),
    NOMBRE VARCHAR2(10) UNIQUE,
    DIRECCION VARCHAR2(10),
    TITULACION VARCHAR2(10),
    SUELDO NUMBER(5) NOT NULL,
    CONSTRAINT PK_PROFESOR PRIMARY KEY (DNI_PROFESOR)
)

ALTER TABLE CURSO ADD DNI_PROFESOR VARCHAR2(10);
ALTER TABLE CURSO ADD CONSTRAINT FK_CURSO FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESOR (DNI_PROFESOR);
ALTER TABLE CURSO ADD CONSTRAINT FECHA_INICIO CHECK (FECHA_INICIO<FECHA_FINALIZACION);
ALTER TABLE ALUMNO ADD CONSTRAINT SEXO CHECK (SEXO LIKE 'M' OR SEXO LIKE 'H');


