--DROP CONSTRAINT BARCOS
--DROP CONSTRAINT LOTES
--DROP CONSTRAINT ESPECIE
--DROP CONSTRAINT CALADERO
--DROP CONSTRAINT FECHAS_CAPTURAS_PERMITIDAS

CREATE TABLE BARCOS
(
    MATRICULA VARCHAR2(10),
    NOMBRE VARCHAR2(10),
    CLASE VARCHAR2(5),
    ARMADOR BOOLEAN,
    CAPACIDAD NUMBER(5),
    NACIONALIDAD VARCHAR2(10),
    CONSTRAINT PK_BARCOS PRIMARY KEY (MATRICULA)
);

CREATE TABLE LOTES
(
    CODIGO VARCHAR2(10),
    MATRICULA VARCHAR2(10),
    NUM_KILOS NUMBER(5),
    PRECIO_POR_KILO_SALIDA NUMBER(4,3),
    PRECIO_POR_KILO_ADJUDICADO NUMBER(4,3),
    FECHA_VENTA DATE NOT NULL,
    CONSTRAINT PK_LOTES PRIMARY KEY (CODIGO),
    CONSTRAINT FK1_LOTES FOREIGN KEY (MATRICULA) REFERENCES BARCOS(MATRICULA) ON DELETE CASCADE
);

CREATE TABLE ESPECIE
(
    CODIGO_ESPECIE VARCHAR2(10),
    NOMBRE VARCHAR2(10),
    TIPO VARCHAR2(10),
    CUPO_POR_BARCO NUMBER(4),
    CONSTRAINT PK_ESPECIE PRIMARY KEY (CODIGO_ESPECIE)
);

CREATE TABLE CALADERO
(
    COD_CALADERO VARCHAR2(10),
    NOMBRE VARCHAR2(10),
    UBICACION VARCHAR2(10),
    ESPECIE_PRINCIPAL VARCHAR2(10),
    CONSTRAINT PK_CALADERO PRIMARY KEY (COD_CALADERO),
    CONSTRAINT FK_CALADERO FOREIGN KEY (ESPECIE_PRINCIPAL) REFERENCES ESPECIE(CODIGO_ESPECIE),
);

CREATE TABLE FECHAS_CAPTURAS_PERMITIDAS
(
    COD_ESPECIE VARCHAR2(10),
    COD_CALADERO VARCHAR2(10),
    FECHA_INICIAL DATE,
    FECHA_FINAL DATE,
    CONSTRAINT PK_FECHAS_CAPTURAS_PERMITIDAS PRIMARY KEY (COD_ESPECIE,COD_CALADERO),
    CONSTRAINT FK1_FECHA_CAPTURAS_PERMITIDAS FOREIGN KEY (COD_ESPECIE) REFERENCES ESPECIE(CODIGO_ESPECIE),
    CONSTRAINT FK2_FECHA_CAPTURAS_PERMITIDAS FOREIGN KEY (COD_CALADERO) REFERENCES CALADERO(COD_CALADERO)
);

ALTER TABLE LOTES ADD CODIGO_ESPECIE VARCHAR2(10);
ALTER TABLE LOTES ADD CONSTRAINT FK2_LOTES FOREIGN KEY (COD_ESPECIE) REFERENCES ESPECIE(CODIGO_ESPECIE) ON DELETE CASCADE;
ALTER TABLE ESPECIE ADD CALADERO_PRINCIPAL VARCHAR2(10);
ALTER TABLE ESPECIE ADD CONSTRAINT FK_ESPECIE FOREIGN KEY (CALADERO_PRINCIPAL) REFERENCES CALADERO(COD_CALADERO) ON DELETE SET NULL;
ALTER TABLE BARCOS ADD CONSTRAINT MATRICULA CHECK ((REGEXP_LIKE(MATRICULA, [A-Z]{2}-[0-9]{4})));
ALTER TABLE LOTES ADD CONSTRAINT PRECIO_POR_KILO_ADJUDICADO CHECK (PRECIO_POR_KILO_ADJUDICADO > PRECIO_POR_KILO_SALIDA)
ALTER TABLE LOTES ADD CONSTRAINT NUM_KILOS CHECK (NUM_KILOS > 0);
ALTER TABLE LOTES ADD CONSTRAINT PRECIO_POR_KILO_ADJUDICADO CHECK (PRECIO_POR_KILO_ADJUDICADO > 0);
ALTER TABLE LOTES ADD CONSTRAINT PRECIO_POR_KILO_SALIDA CHECK (PRECIO_POR_KILO_SALIDA > 0);
ALTER TABLE CALADERO ADD CONSTRAINT NOMBRE CHECK ((NOMBRE=UPPER(NOMBRE)));
ALTER TABLE CALADERO ADD CONSTRAINT UBICACION CHECK ((UBICACION=UPPER(UBICACION)));
ALTER TABLE CALADERO ADD CONSTRAINT FECHA_INICIAL CHECK (TO_CHAR(FECHA_INICIAL,'MM/DD') < '02/02' OR TO_CHAR(FECHA_INICIAL,'MM/DD') > '03/28');
 ((EXTRACT (MONTH FROM FECHA_INICIAL))[^2]) AND ((EXTRACT (DAY FROM FECHA_INICIAL))>28) IN ((EXTRACT (MONTH FROM FECHA_INICIAL))[3])
ALTER TABLE CALADERO ADD NOMBRE_CIENTIFICO VARCHAR2(10);
ALTER TABLE BARCO DROP COLUMN ARMADOR;