--DROP TABLE JUGADORES
--DROP TABLE EQUIPOS
--DROP TABLE PARTIDOS
--DROP TABLE INCIDENCIAS

CREATE TABLE EQUIPOS
(
	COD_EQUIPO VARCHAR2(4),
	NOMBRE VARCHAR2(30) NOT NULL,
	LOCALIDAD VARCHAR2(15),
	CONSTRAINT PK_EQUIPOS PRIMARY KEY (COD_EQUIPO)
);

CREATE TABLE JUGADORES
(
	COD_JUGADOR VARCHAR2(4),
	NOMBRE VARCHAR2(30) NOT NULL,
	FECHA_NACIMIENTO DATE,
	DEMARCACION VARCHAR2(10),
	COD_EQUIPO VARCHAR2(4),
	CONSTRAINT PK_JUGADORES PRIMARY KEY (COD_JUGADOR),
	CONSTRAINT FK_JUGADORES FOREIGN KEY (COD_EQUIPO) REFERENCES EQUIPOS (COD_EQUIPO)
);

CREATE TABLE PARTIDOS 
(
	COD_PARTIDO VARCHAR2(4),
	COD_EQUIPOLOCAL VARCHAR2(4),
	COD_EQUIPOVISITANTE VARCHAR2(4),
	FECHA DATE,
	COMPETICION VARCHAR2(4),
	JORNADA VARCHAR2(20),
	CONSTRAINT PK_PARTIDOS PRIMARY KEY (COD_PARTIDO),
	CONSTRAINT FK1_PARTIDOS FOREIGN KEY (COD_EQUIPO_LOCAL) REFERENCES EQUIPO (COD_EQUIPO),
	CONSTRAINT FK2_PARTIDOS FOREIGN KEY (COD_EQUIPO_VISITANTE) REFERENCES EQUIPO (COD_EQUIPO),
	CONSTRAINT FECHA CHECK (EXTRACT(MONTH(FECHA,NOT IN ('07','09')))),
	CONSTRAINT COMPETICION CHECK (COMPETICION,(IN ('COPA','LIGA')))
);

CREATE TABLE INCIDENCIAS
(
	
	NUM_INCIDENCIA VARCHAR2(6),
	COD_PARTIDO VARCHAR2(4),
	COD_JUGADOR VARCHAR2(4),
	MINUTO NUMBER(2),
	TIPO VARCHAR2(20),
	CONSTRAINT PK_INCIDENCIAS PRIMARY KEY (NUM_INCIDENCIA),
	CONSTRAINT FK1_INCIDENCIAS FOREIGN KEY (COD_PARTIDO) REFERENCES PARTIDOS (COD_PARTIDO),
 	CONSTRAINT FK2_INCIDENCIAS FOREIGN KEY (COD_JUGADOR) REFERENCES JUGADORES (COD_JUGADOR),
	CONSTRAINT MINUTO CHECK (MINUTO>0 AND MINUTO<101)
)

ALTER TABLE JUGADORES ADD CONSTRAINT NOMBRE CHECK (^[A-Z]{1}[a-z]*);
ALTER TABLE JUGADORES ADD CONSTRAINT DEMARCACION CHECK (DEMARCACION, IN ('PORTERO','DEFENSA','MEDIO','DELANTERO'));
ALTER TABLE EQUIPOS ADD CONSTRAINT COD_EQUIPO CHECK (^[0-9]{1});
ALTER TABLE INCIDENCIAS MODIFY TIPO VARCHAR2(20) NOT NULL;
ALTER TABLE EQUIPOS ADD GOLES_MARCADOS NUMBER(3);