--DROP TABLE VEHICULOS 
--DROP TABLE CLIENTES 
--DROP TABLE ALQUILERES

CREATE TABLE VEHICULOS
(
	MATRICULA VARCHAR2(7),
	MARCA VARCHAR2(10) NOT NULL,
	MODELO VARCHAR2(10) NOT NULL,
	FECHA_COMPRA DATE,
	PRECIO_POR_DIA NUMBER(5,2),
	CONSTRAINT PK_VEHICULOS PRIMARY KEY (MATRICULA),
	CONSTRAINT FECHA_COMPRA CHECK ((EXTRACT (YEAR FROM FECHA_COMPRA))> 2001),
	CONSTRAINT PRECIO_POR_DIA CHECK (PRECIO_POR_DIA > 0)
);

CREATE TABLE CLIENTES 
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(30) NOT NULL,
	NACIONALIDAD VARCHAR2(30) NOT NULL,
	FECHA_NACIMIENTO DATE,
	DIRECCION VARCHAR2(50),
	CONSTRAINT PK_CLIENTES PRIMARY KEY (DNI)
);

CREATE TABLE ALQUILERES
(
	MATRICULA VARCHAR2(7) NOT NULL,
	DNI VARCHAR2(10) NOT NULL,
	FECHA_HORA DATE,
	NUM_DIAS NUMBER(2),
	KILOMETROS NUMBER(4) DEFAULT 0,
	CONSTRAINT PK_ALQUILERES PRIMARY KEY (MATRICULA,DNI,FECHA_HORA),
	CONSTRAINT FK1_ALQUILERES FOREIGN KEY (MATRICULA) REFERENCES VEHICULOS (MATRICULA),
	CONSTRAINT FK2_ALQUILERES FOREIGN KEY (DNI) REFERENCES CLIENTES (DNI)
)
ALTER TABLE CLIENTES ADD CONSTRAINT DNI CHECK (REGEXP_LIKE(DNI,'^[0-9]{8}-[a-z]{1}$'));
ALTER TABLE VEHICULOS ADD CONSTRAINT MATRICULA CHECK (REGEXP_LIKE(MATRICULA,'^[0-9]{4}[A-Z]{3}$'));
ALTER TABLE VEHICULOS ADD KILOMETROS_TOTALES NUMBER(6);

	